config/routes.rb
Rails.application.routes.draw do

	resources :wikis do
		resources :collaborators, only: [:create, :destroy]
	end
	
	resources :charges, only: [:new, :create]
	
	devise_for :users

  	get 'about' => 'welcome#about'

  	root to: 'welcome#index'
end

app/models/amount.rb
class Amount 

	def self.default
		10_00
	end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :wikis
  has_many :collaborators

  after_initialize :init

  def init
  	self.role ||= true if self.role.nil?
  end

  def admin?
  	role == 'admin'
  end

  def standard?
  	role == 'standard'
  end

  def premium?
  	role == 'premium'
  end
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
	belongs_to :user  # the user that created the wiki
	has_many :collaborators
	has_many :users, through: :collaborators  # the users that are collaborators

	scope :privatewiki, -> { where(private: true) }
	scope :publicwiki, -> { where(private: false) }

	def self.visible_to(user)
		user && ["admin", "premium"].include?(user.role) ? self.all : self.publicwiki
	end

	def collaborator_for(user)
		self.collaborators.where(user_id: user.id).first
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pundit
  	protect_from_forgery with: :exception
  	before_action :configure_permitted_parameters, if: :devise_controller?

  	rescue_from Pundit::NotAuthorizedError do |exception|
  		redirect_to root_url, alert: exception.message
  	end

  	protected

  	def configure_permitted_parameters
  		devise_parameter_sanitizer.for(:sign_up) << :name
  	end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
   
     # Creates a Stripe Customer object, for associating
     # with the charge
     customer = Stripe::Customer.create(
       email: current_user.email,
       card: params[:stripeToken]
     )
   
     # Where the real magic happens
     charge = Stripe::Charge.create(
       customer: customer.id, # Note -- this is NOT the user_id in your app
       amount: Amount.default,
       description: "BigMoney Membership - #{current_user.email}",
       currency: 'usd'
     )

     current_user.update_attribute(:role, "premium")
   
     flash[:success] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
     redirect_to root_path # or wherever
   
   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:error] = e.message
     redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.name}",
     amount: Amount.default
   }
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
	before_action :set_wiki

	def create
		@collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])
	    if @collaborator.save
	  		flash[:notice] = "Collaborator was added."
	  		redirect_to edit_wiki_path(@wiki)
	  	else
	  		flash[:error] = "There was a problem adding your collaborator. Please try again."
	  		redirect_to edit_wiki_path(@wiki)
	  	end
	end

	def destroy
		@collaborator = Collaborator.find(params [:id])
		if @collaborator.destroy
  			flash[:notice] = "Collaborator was utterly destroyed!"
  			redirect_to edit_wiki_path(@wiki)
  		else
  			flash[:error] = "There was an error destroying your collaborator. Please try again."
  			redirect_to edit_wiki_path(@wiki)
  		end
	end

	private 

	def set_wiki
		@wiki = Wiki.find(params[:wiki_id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
  	@wikis = Wiki.visible_to(current_user)
    authorize @wikis
  end

  def show
  	@wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def new
  	@wiki = Wiki.new
    authorize @wiki
  end

  def create
  	@wiki = Wiki.new(wiki_params)
    authorize @wiki
  	if @wiki.save
  		flash[:notice] = "Wiki was saved."
  		redirect_to @wiki
  	else
  		flash[:error] = "There was a problem saving your wiki. Please try again."
  		render :new
  	end
  end

  def edit
  	@wiki = Wiki.find(params[:id])
    @users = User.all.select {|user| user != current_user}
  end

  def update
  	@wiki = Wiki.find(params[:id])
  	if @wiki.update_attributes(wiki_params)
  		flash[:notice] = "Wiki was successfully updated."
  		redirect_to @wiki
  	else
  		flash[:error] = "There was a problem updating your wiki.  Please try again!"
  		render :edit
  	end
  end

  def destroy
  	@wiki = Wiki.find(params[:id])
  	if @wiki.destroy
  		flash[:notice] = "Wiki was utterly destroyed!"
  		redirect_to wikis_path
  	else
  		flash[:error] = "There was an error destroying your wiki. Please try again."
  		redirect_to @wiki
  	end
  end

  private

  def wiki_params
  	params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def markdown(text)
		renderer = Redcarpet::Render::HTML.new
  		extensions = {fenced_code_blocks: true}
  		redcarpet = Redcarpet::Markdown.new(renderer, extensions)
  		(redcarpet.render text).html_safe
  	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
 <%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
   <%= stylesheet_link_tag 'bootstrap.min', media: 'all' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="container">

		<ul class="nav nav-tabs">
			<li><%= link_to "Blocipedia", root_path %></li>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Wikis", wikis_path %></li>
			<div class="pull-right user-info">
			<% if current_user %>
				Hello <%= current_user.email %>! <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
				<%= link_to "Upgrade to Premium", new_charge_path %>
			<% elsif %>
				<%= link_to "Sign In", new_user_session_path %>
				<%= link_to "Sign Up", new_user_registration_path %>
			<% end %>
		</div>



		</ul>
		
			

			<% if flash[:notice] %>
			<div class="alert alert-success">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= flash[:notice] %>
			</div>
			<% elsif flash[:error] %>
			<div class="alert alert-danger">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= flash[:error] %>
			</div>
			<% elsif flash[:alert] %>
			<div class="alert alert-warning">
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= flash[:alert] %>
			</div>
			<% end %>




		<%= yield %>
			</div>

</body>
</html>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Not sure exactly what I'm going to put here yet, but I'll think of something.</p>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
	<h1>Blocipedia!</h1>
	<p id ="index-body">Wikipedia's inferior and forgotten and younger sibling</p>

	<p>

		<%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
		<%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>

	</p>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>No cat pictures.  There's enough of that all over the rest of the internets.  Don't need none of that here.  Picture of pigeons, however, are highly encouraged!</li>
      <li>No cupcakes! They're like cakes, but without the effort.</li>
      <li>If you're Justin Bieber, or a Bieberite or whatever the hell those things that are infatuated with him call themselves, just leave.  Please, just go away.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>
<div class="row">
  <h4>Collaborators</h4>
  <table class="table">
    <thead>
      <th>Email</th>
      <th></th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td>
            <% unless @wiki.users.include?(user) %>
              <!--  create button -->
              <%= link_to "Add as Collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: "btn btn-success" %>
            <% else %>
              <!-- destroy button -->
              <%= link_to "Destroy Collaborator", wiki_collaborator_path(@wiki, @wiki.collaborator_for(user)), method: :delete, class: "btn btn-danger" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/wikis/index.html.erb
<h1>Wikis!  All of 'em.</h1>
<%= link_to "Create New Wiki", new_wiki_path, class: 'btn btn-success' %>
<% @wikis.each do |wiki| %>
<div class="media">
	<div class="media-body">
		<h4 class="media-heading">
			<%= link_to wiki.title, wiki %>
		</h4>
	</div>
</div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
	<div class="col-md-4">
		<p>Guidelines for wikis</p>
		<ul>
			<li>No cat pictures.  There's enough of that all over the rest of the internets.  Don't need none of that here.  Picture of pigeons, however, are highly encouraged!</li>
			<li>No cupcakes! They're like cakes, but without the effort.</li>
			<li>If you're Justin Bieber, or a Bieberite or whatever the hell those things that are infatuated with him call themselves, just leave.  Please, just go away.</li>
		</ul>
	</div>
	<div class="col-md-8">
		<%= form_for @wiki do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
		</div>
		<div class="form-group">
			<%= f.label :body %>
			<%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
		</div>
		<% if current_user.admin? || current_user.premium? %>
		  <div class="form-group">
		  	<%= f.label :private, class: 'checkbox' do%>
		  	<%= f.check_box :private  %> Private wiki
		  	<% end %>
		  </div>
		<% end %>
		<div class="form-group">
			<%= f.submit "Save", class: 'btn btn-success' %>
		</div>
		<% end %>
	</div>
</div>

app/views/wikis/show.html.erb
<h1><%= markdown @wiki.title %></h1>
<p><%= markdown @wiki.body %></p>

<%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>

<%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %>